//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.421.0.
namespace PaymentechCore.Models.RequestModels
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("baseElementsType", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BaseElementsType
    {

        [System.Xml.Serialization.XmlElementAttribute("IndustryType")]
        public Valid_Industry_Types IndustryType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CardBrand")]
        public string CardBrand { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AccountNum")]
        public string AccountNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("Exp")]
        public string Exp { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CurrencyCode")]
        public string CurrencyCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CurrencyExponent")]
        public string CurrencyExponent { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CardSecValInd")]
        public string CardSecValInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CardSecVal")]
        public string CardSecVal { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BCRtNum")]
        public string BCRtNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CheckDDA")]
        public string CheckDDA { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BankAccountType")]
        public string BankAccountType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPAuthMethod")]
        public string ECPAuthMethod { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BankPmtDelv")]
        public string BankPmtDelv { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSzip")]
        public string AVSzip { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSaddress1")]
        public string AVSaddress1 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSaddress2")]
        public string AVSaddress2 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVScity")]
        public string AVScity { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSstate")]
        public string AVSstate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSphoneNum")]
        public string AVSphoneNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSname")]
        public string AVSname { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVScountryCode")]
        public string AVScountryCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDestzip")]
        public string AVSDestzip { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDestaddress1")]
        public string AVSDestaddress1 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDestaddress2")]
        public string AVSDestaddress2 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDestcity")]
        public string AVSDestcity { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDeststate")]
        public string AVSDeststate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDestphoneNum")]
        public string AVSDestphoneNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDestname")]
        public string AVSDestname { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDestcountryCode")]
        public string AVSDestcountryCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("UseCustomerRefNum")]
        public string UseCustomerRefNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AuthenticationECIInd")]
        public string AuthenticationECIInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CAVV")]
        public string CAVV { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("XID")]
        public string XID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AAV")]
        public string AAV { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrderID")]
        public string OrderID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("Amount")]
        public string Amount { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("Comments")]
        public string Comments { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDCountryCode")]
        public string EUDDCountryCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDBankSortCode")]
        public string EUDDBankSortCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDRibCode")]
        public string EUDDRibCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLCustomerIP")]
        public string BMLCustomerIP { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLCustomerEmail")]
        public string BMLCustomerEmail { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLShippingCost")]
        public string BMLShippingCost { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLTNCVersion")]
        public string BMLTNCVersion { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLCustomerRegistrationDate")]
        public string BMLCustomerRegistrationDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLCustomerTypeFlag")]
        public string BMLCustomerTypeFlag { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLItemCategory")]
        public string BMLItemCategory { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLPreapprovalInvitationNum")]
        public string BMLPreapprovalInvitationNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLMerchantPromotionalCode")]
        public string BMLMerchantPromotionalCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLCustomerBirthDate")]
        public string BMLCustomerBirthDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLCustomerSSN")]
        public string BMLCustomerSSN { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLCustomerAnnualIncome")]
        public string BMLCustomerAnnualIncome { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLCustomerResidenceStatus")]
        public string BMLCustomerResidenceStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLCustomerCheckingAccount")]
        public string BMLCustomerCheckingAccount { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLCustomerSavingsAccount")]
        public string BMLCustomerSavingsAccount { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLProductDeliveryType")]
        public string BMLProductDeliveryType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BillerReferenceNumber")]
        public string BillerReferenceNumber { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("UseStoredAAVInd")]
        public string UseStoredAAVInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPCheckSerialNumber")]
        public string ECPCheckSerialNumber { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPTerminalCity")]
        public string ECPTerminalCity { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPTerminalState")]
        public string ECPTerminalState { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPImageReferenceNumber")]
        public string ECPImageReferenceNumber { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerAni")]
        public string CustomerAni { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSPhoneType")]
        public string AVSPhoneType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDestPhoneType")]
        public string AVSDestPhoneType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerEmail")]
        public string CustomerEmail { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerIpAddress")]
        public string CustomerIpAddress { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EmailAddressSubtype")]
        public string EmailAddressSubtype { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerBrowserName")]
        public string CustomerBrowserName { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ShippingMethod")]
        public string ShippingMethod { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDBankBranchCode")]
        public string EUDDBankBranchCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDIBAN")]
        public string EUDDIBAN { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDBIC")]
        public string EUDDBIC { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("DWWalletID")]
        public string DWWalletID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("DWSLI")]
        public string DWSLI { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("DWIncentiveInd")]
        public string DWIncentiveInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("DigitalWalletType")]
        public string DigitalWalletType { get; set; }
    }

    /// <summary>
    /// <para>New order Industry Types</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("New order Industry Types")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("valid-industry-types", Namespace = "")]
    public enum Valid_Industry_Types
    {

        /// <summary>
        /// <para>Ecommerce transaction</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Ecommerce transaction")]
        EC,

        /// <summary>
        /// <para>Recurring Payment transaction</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Recurring Payment transaction")]
        RC,

        /// <summary>
        /// <para>Mail Order Telephone Order transaction</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Mail Order Telephone Order transaction")]
        MO,

        /// <summary>
        /// <para>Interactive Voice Response</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Interactive Voice Response")]
        IV,

        /// <summary>
        /// <para>Interactive Voice Response</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Interactive Voice Response")]
        IN,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("softMerchantDescriptorsType", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SoftMerchantDescriptorsType
    {

        [System.Xml.Serialization.XmlElementAttribute("SMDDBA")]
        public string SMDDBA { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SMDMerchantID")]
        public string SMDMerchantID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SMDContactInfo")]
        public string SMDContactInfo { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SMDStreet")]
        public string SMDStreet { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SMDCity")]
        public string SMDCity { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SMDRegion")]
        public string SMDRegion { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SMDPostalCode")]
        public string SMDPostalCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SMDCountryCode")]
        public string SMDCountryCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SMDMCC")]
        public string SMDMCC { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SMDEmail")]
        public string SMDEmail { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SMDPhoneNumber")]
        public string SMDPhoneNumber { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("fraudAnalysisType", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FraudAnalysisType
    {

        [System.Xml.Serialization.XmlElementAttribute("FraudScoreIndicator")]
        public string FraudScoreIndicator { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RulesTrigger")]
        public string RulesTrigger { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SafetechMerchantID")]
        public string SafetechMerchantID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("KaptchaSessionID")]
        public string KaptchaSessionID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("WebsiteShortName")]
        public string WebsiteShortName { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CashValueOfFencibleItems")]
        public string CashValueOfFencibleItems { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerDOB")]
        public string CustomerDOB { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerGender")]
        public string CustomerGender { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerDriverLicense")]
        public string CustomerDriverLicense { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerID")]
        public string CustomerID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerIDCreationTime")]
        public string CustomerIDCreationTime { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("KTTVersionNumber")]
        public string KTTVersionNumber { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("KTTDataLength")]
        public string KTTDataLength { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("KTTDataString")]
        public string KTTDataString { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PinlessDebitTxnType")]
        public string PinlessDebitTxnType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PinlessDebitMerchantUrl")]
        public string PinlessDebitMerchantUrl { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("safetechFraudAnalysisType", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SafetechFraudAnalysisType
    {

        [System.Xml.Serialization.XmlElementAttribute("OrbitalConnectionUsername")]
        public string OrbitalConnectionUsername { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrbitalConnectionPassword")]
        public string OrbitalConnectionPassword { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BIN")]
        public Valid_Routing_Bins BIN { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MerchantID")]
        public string MerchantID { get; set; }

        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 3.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(3)]
        [System.Xml.Serialization.XmlElementAttribute("TerminalID")]
        public string TerminalID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BaseElements")]
        public BaseElementsType BaseElements { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FraudAnalysis")]
        public FraudAnalysisType FraudAnalysis { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("valid-routing-bins", Namespace = "")]
    public enum Valid_Routing_Bins
    {

        /// <summary>
        /// <para>Stratus</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Stratus")]
        [System.Xml.Serialization.XmlEnumAttribute("000001")]
        Item000001,

        /// <summary>
        /// <para>Tandam</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tandam")]
        [System.Xml.Serialization.XmlEnumAttribute("000002")]
        Item000002,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("newOrderType", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewOrderType
    {

        [System.Xml.Serialization.XmlElementAttribute("OrbitalConnectionUsername")]
        public string OrbitalConnectionUsername { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrbitalConnectionPassword")]
        public string OrbitalConnectionPassword { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("IndustryType")]
        public Valid_Industry_Types IndustryType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MessageType")]
        public Valid_Trans_Types MessageType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BIN")]
        public Valid_Routing_Bins BIN { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MerchantID")]
        public string MerchantID { get; set; }

        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 3.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(3)]
        [System.Xml.Serialization.XmlElementAttribute("TerminalID")]
        public string TerminalID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CardBrand")]
        public string CardBrand { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AccountNum")]
        public string AccountNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("Exp")]
        public string Exp { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CurrencyCode")]
        public string CurrencyCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CurrencyExponent")]
        public string CurrencyExponent { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CardSecValInd")]
        public string CardSecValInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CardSecVal")]
        public string CardSecVal { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("DebitCardIssueNum")]
        public string DebitCardIssueNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("DebitCardStartDate")]
        public string DebitCardStartDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BCRtNum")]
        public string BCRtNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CheckDDA")]
        public string CheckDDA { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BankAccountType")]
        public string BankAccountType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPAuthMethod")]
        public string ECPAuthMethod { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BankPmtDelv")]
        public string BankPmtDelv { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSzip")]
        public string AVSzip { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSaddress1")]
        public string AVSaddress1 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSaddress2")]
        public string AVSaddress2 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVScity")]
        public string AVScity { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSstate")]
        public string AVSstate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSphoneNum")]
        public string AVSphoneNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSname")]
        public string AVSname { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVScountryCode")]
        public string AVScountryCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDestzip")]
        public string AVSDestzip { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDestaddress1")]
        public string AVSDestaddress1 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDestaddress2")]
        public string AVSDestaddress2 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDestcity")]
        public string AVSDestcity { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDeststate")]
        public string AVSDeststate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDestphoneNum")]
        public string AVSDestphoneNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDestname")]
        public string AVSDestname { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDestcountryCode")]
        public string AVSDestcountryCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerProfileFromOrderInd")]
        public string CustomerProfileFromOrderInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerRefNum")]
        public string CustomerRefNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerProfileOrderOverrideInd")]
        public string CustomerProfileOrderOverrideInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("Status")]
        public string Status { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AuthenticationECIInd")]
        public string AuthenticationECIInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CAVV")]
        public string CAVV { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("XID")]
        public string XID { get; set; }

        /// <summary>
        /// <para xml:lang="en">Maximum length: 6.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(6)]
        [System.Xml.Serialization.XmlElementAttribute("PriorAuthID")]
        public string PriorAuthID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrderID")]
        public string OrderID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("Amount")]
        public string Amount { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("Comments")]
        public string Comments { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ShippingRef")]
        public string ShippingRef { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TaxInd")]
        public string TaxInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("Tax")]
        public string Tax { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AMEXTranAdvAddn1")]
        public string AMEXTranAdvAddn1 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AMEXTranAdvAddn2")]
        public string AMEXTranAdvAddn2 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AMEXTranAdvAddn3")]
        public string AMEXTranAdvAddn3 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AMEXTranAdvAddn4")]
        public string AMEXTranAdvAddn4 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AAV")]
        public string AAV { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SDMerchantName")]
        public string SDMerchantName { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SDProductDescription")]
        public string SDProductDescription { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SDMerchantCity")]
        public string SDMerchantCity { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SDMerchantPhone")]
        public string SDMerchantPhone { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SDMerchantURL")]
        public string SDMerchantURL { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SDMerchantEmail")]
        public string SDMerchantEmail { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RecurringInd")]
        public string RecurringInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDCountryCode")]
        public string EUDDCountryCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDBankSortCode")]
        public string EUDDBankSortCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDRibCode")]
        public string EUDDRibCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLCustomerIP")]
        public string BMLCustomerIP { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLCustomerEmail")]
        public string BMLCustomerEmail { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLShippingCost")]
        public string BMLShippingCost { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLTNCVersion")]
        public string BMLTNCVersion { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLCustomerRegistrationDate")]
        public string BMLCustomerRegistrationDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLCustomerTypeFlag")]
        public string BMLCustomerTypeFlag { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLItemCategory")]
        public string BMLItemCategory { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLPreapprovalInvitationNum")]
        public string BMLPreapprovalInvitationNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLMerchantPromotionalCode")]
        public string BMLMerchantPromotionalCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLCustomerBirthDate")]
        public string BMLCustomerBirthDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLCustomerSSN")]
        public string BMLCustomerSSN { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLCustomerAnnualIncome")]
        public string BMLCustomerAnnualIncome { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLCustomerResidenceStatus")]
        public string BMLCustomerResidenceStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLCustomerCheckingAccount")]
        public string BMLCustomerCheckingAccount { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLCustomerSavingsAccount")]
        public string BMLCustomerSavingsAccount { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BMLProductDeliveryType")]
        public string BMLProductDeliveryType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BillerReferenceNumber")]
        public string BillerReferenceNumber { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBType")]
        public string MBType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBOrderIdGenerationMethod")]
        public string MBOrderIdGenerationMethod { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBRecurringStartDate")]
        public string MBRecurringStartDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBRecurringEndDate")]
        public string MBRecurringEndDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBRecurringNoEndDateFlag")]
        public string MBRecurringNoEndDateFlag { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBRecurringMaxBillings")]
        public string MBRecurringMaxBillings { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBRecurringFrequency")]
        public string MBRecurringFrequency { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBDeferredBillDate")]
        public string MBDeferredBillDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBMicroPaymentMaxDollarValue")]
        public string MBMicroPaymentMaxDollarValue { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBMicroPaymentMaxBillingDays")]
        public string MBMicroPaymentMaxBillingDays { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBMicroPaymentMaxTransactions")]
        public string MBMicroPaymentMaxTransactions { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TxRefNum")]
        public string TxRefNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCOrderNum")]
        public string PCOrderNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCDestZip")]
        public string PCDestZip { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCDestName")]
        public string PCDestName { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCDestAddress1")]
        public string PCDestAddress1 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCDestAddress2")]
        public string PCDestAddress2 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCDestCity")]
        public string PCDestCity { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCDestState")]
        public string PCDestState { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3FreightAmt")]
        public string PC3FreightAmt { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3DutyAmt")]
        public string PC3DutyAmt { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3DestCountryCd")]
        public string PC3DestCountryCd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3ShipFromZip")]
        public string PC3ShipFromZip { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3DiscAmt")]
        public string PC3DiscAmt { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3VATtaxAmt")]
        public string PC3VATtaxAmt { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3VATtaxRate")]
        public string PC3VATtaxRate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3AltTaxInd")]
        public string PC3AltTaxInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3AltTaxAmt")]
        public string PC3AltTaxAmt { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3LineItemCount")]
        public string PC3LineItemCount { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PC3LineItemType> _pC3LineItemArray;

        [System.Xml.Serialization.XmlArrayAttribute("PC3LineItemArray")]
        [System.Xml.Serialization.XmlArrayItemAttribute("PC3LineItem")]
        public System.Collections.ObjectModel.Collection<PC3LineItemType> PC3LineItemArray
        {
            get
            {
                return this._pC3LineItemArray;
            }
            private set
            {
                this._pC3LineItemArray = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die PC3LineItemArray-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the PC3LineItemArray collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PC3LineItemArraySpecified
        {
            get
            {
                return (this.PC3LineItemArray.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="NewOrderType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="NewOrderType" /> class.</para>
        /// </summary>
        public NewOrderType()
        {
            this._pC3LineItemArray = new System.Collections.ObjectModel.Collection<PC3LineItemType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("PartialAuthInd")]
        public string PartialAuthInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AccountUpdaterEligibility")]
        public string AccountUpdaterEligibility { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("UseStoredAAVInd")]
        public string UseStoredAAVInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPActionCode")]
        public string ECPActionCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPCheckSerialNumber")]
        public string ECPCheckSerialNumber { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPTerminalCity")]
        public string ECPTerminalCity { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPTerminalState")]
        public string ECPTerminalState { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPImageReferenceNumber")]
        public string ECPImageReferenceNumber { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerAni")]
        public string CustomerAni { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSPhoneType")]
        public string AVSPhoneType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDestPhoneType")]
        public string AVSDestPhoneType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerEmail")]
        public string CustomerEmail { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerIpAddress")]
        public string CustomerIpAddress { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EmailAddressSubtype")]
        public string EmailAddressSubtype { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerBrowserName")]
        public string CustomerBrowserName { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ShippingMethod")]
        public string ShippingMethod { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FraudAnalysis")]
        public FraudAnalysisType FraudAnalysis { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SoftMerchantDescriptors")]
        public SoftMerchantDescriptorsType SoftMerchantDescriptors { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CardIndicators")]
        public string CardIndicators { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDBankBranchCode")]
        public string EUDDBankBranchCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDIBAN")]
        public string EUDDIBAN { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDBIC")]
        public string EUDDBIC { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDMandateSignatureDate")]
        public string EUDDMandateSignatureDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDMandateID")]
        public string EUDDMandateID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDMandateType")]
        public string EUDDMandateType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PaymentInd")]
        public string PaymentInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TxnSurchargeAmt")]
        public string TxnSurchargeAmt { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PaymentActionInd")]
        public string PaymentActionInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("DPANInd")]
        public string DPANInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AEVV")]
        public string AEVV { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("DWWalletID")]
        public string DWWalletID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("DWSLI")]
        public string DWSLI { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("DWIncentiveInd")]
        public string DWIncentiveInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("DigitalWalletType")]
        public string DigitalWalletType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PRBirthDate")]
        public string PRBirthDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PRMaskedAccountNumber")]
        public string PRMaskedAccountNumber { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PRPartialPostalCode")]
        public string PRPartialPostalCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PRLastName")]
        public string PRLastName { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TokenRequestorID")]
        public string TokenRequestorID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCardRequestorName")]
        public string PCardRequestorName { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCardLocalTaxRate")]
        public string PCardLocalTaxRate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCardNationalTax")]
        public string PCardNationalTax { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCardPstTaxRegNumber")]
        public string PCardPstTaxRegNumber { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCardCustomerVatRegNumber")]
        public string PCardCustomerVatRegNumber { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCardMerchantVatRegNumber")]
        public string PCardMerchantVatRegNumber { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCardTotalTaxAmount")]
        public string PCardTotalTaxAmount { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCardDtlTaxAmount1Ind")]
        public string PCardDtlTaxAmount1Ind { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCardDtlTaxAmount1")]
        public string PCardDtlTaxAmount1 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCardDtlTaxAmount2Ind")]
        public string PCardDtlTaxAmount2Ind { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCardDtlTaxAmount2")]
        public string PCardDtlTaxAmount2 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("DigitalTokenCryptogram")]
        public string DigitalTokenCryptogram { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCardNationalTaxRate")]
        public string PCardNationalTaxRate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCardLocalTaxAmount")]
        public string PCardLocalTaxAmount { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSFirstName")]
        public string EWSFirstName { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSMiddleName")]
        public string EWSMiddleName { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSLastName")]
        public string EWSLastName { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSBusinessName")]
        public string EWSBusinessName { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSAddressLine1")]
        public string EWSAddressLine1 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSAddressLine2")]
        public string EWSAddressLine2 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSCity")]
        public string EWSCity { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSState")]
        public string EWSState { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSZip")]
        public string EWSZip { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSPhoneType")]
        public string EWSPhoneType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSPhoneNumber")]
        public string EWSPhoneNumber { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSCheckSerialNumber")]
        public string EWSCheckSerialNumber { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSSSNTIN")]
        public string EWSSSNTIN { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSDOB")]
        public string EWSDOB { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSIDType")]
        public string EWSIDType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSIDNumber")]
        public string EWSIDNumber { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSIDState")]
        public string EWSIDState { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPSameDayInd")]
        public string ECPSameDayInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPReDepositFreq")]
        public string ECPReDepositFreq { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPReDepositInd")]
        public string ECPReDepositInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FXOptoutInd")]
        public string FXOptoutInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FXRateHandlingInd")]
        public string FXRateHandlingInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FXRateID")]
        public string FXRateID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FXExchangeRate")]
        public string FXExchangeRate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FXPresentmentCurrency")]
        public string FXPresentmentCurrency { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FXSettlementCurrency")]
        public string FXSettlementCurrency { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MITMsgType")]
        public string MITMsgType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MITStoredCredentialInd")]
        public string MITStoredCredentialInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MITSubmittedTransactionID")]
        public string MITSubmittedTransactionID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PinlessDebitTxnType")]
        public string PinlessDebitTxnType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PinlessDebitMerchantUrl")]
        public string PinlessDebitMerchantUrl { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RtauOptOutInd")]
        public string RtauOptOutInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PymtBrandProgramCode")]
        public string PymtBrandProgramCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TokenTxnType")]
        public string TokenTxnType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SCATrustedMerchant")]
        public string SCATrustedMerchant { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SCASecureCorporatePayment")]
        public string SCASecureCorporatePayment { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SCATransactionRiskAnalysis")]
        public string SCATransactionRiskAnalysis { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SCALowValuePayment")]
        public string SCALowValuePayment { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SCAMerchantInitiatedTransaction")]
        public string SCAMerchantInitiatedTransaction { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SCARecurringPayment")]
        public string SCARecurringPayment { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SCADelegation")]
        public string SCADelegation { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("DeferredAuth")]
        public string DeferredAuth { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MCProgramProtocol")]
        public string MCProgramProtocol { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MCDirectoryTransID")]
        public string MCDirectoryTransID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("UCAFInd")]
        public string UCAFInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("DsrpCryptogram")]
        public string DsrpCryptogram { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TargetCardBrand")]
        public string TargetCardBrand { get; set; }
    }

    /// <summary>
    /// <para>New order Transaction Types</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("New order Transaction Types")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("valid-trans-types", Namespace = "")]
    public enum Valid_Trans_Types
    {

        /// <summary>
        /// <para>Auth Only No Capture</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Auth Only No Capture")]
        A,

        /// <summary>
        /// <para>Auth and Capture</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Auth and Capture")]
        AC,

        /// <summary>
        /// <para>Force Auth No Capture and no online authorization</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Force Auth No Capture and no online authorization")]
        F,

        /// <summary>
        /// <para>Force Auth No Capture and no online authorization</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Force Auth No Capture and no online authorization")]
        FR,

        /// <summary>
        /// <para>Force Auth and Capture no online authorization</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Force Auth and Capture no online authorization")]
        FC,

        /// <summary>
        /// <para>Refund and Capture no online authorization</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Refund and Capture no online authorization")]
        R,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PC3LineItemArray", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PC3LineItemArray
    {

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PC3LineItemType> _pC3LineItem;

        [System.Xml.Serialization.XmlElementAttribute("PC3LineItem")]
        public System.Collections.ObjectModel.Collection<PC3LineItemType> PC3LineItem
        {
            get
            {
                return this._pC3LineItem;
            }
            private set
            {
                this._pC3LineItem = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="PC3LineItemArray" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PC3LineItemArray" /> class.</para>
        /// </summary>
        public PC3LineItemArray()
        {
            this._pC3LineItem = new System.Collections.ObjectModel.Collection<PC3LineItemType>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PC3LineItemType", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PC3LineItemType
    {

        [System.Xml.Serialization.XmlElementAttribute("PC3DtlIndex")]
        public string PC3DtlIndex { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3DtlDesc")]
        public string PC3DtlDesc { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3DtlProdCd")]
        public string PC3DtlProdCd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3DtlQty")]
        public string PC3DtlQty { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3DtlUOM")]
        public string PC3DtlUOM { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3DtlTaxAmt")]
        public string PC3DtlTaxAmt { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3DtlTaxRate")]
        public string PC3DtlTaxRate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3Dtllinetot")]
        public string PC3Dtllinetot { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3DtlDisc")]
        public string PC3DtlDisc { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3DtlCommCd")]
        public string PC3DtlCommCd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3DtlUnitCost")]
        public string PC3DtlUnitCost { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3DtlGrossNet")]
        public string PC3DtlGrossNet { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3DtlTaxType")]
        public string PC3DtlTaxType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3DtlDiscInd")]
        public string PC3DtlDiscInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3DtlDebitInd")]
        public string PC3DtlDebitInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3DtlDiscountRate")]
        public string PC3DtlDiscountRate { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("markForCaptureType", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MarkForCaptureType
    {

        [System.Xml.Serialization.XmlElementAttribute("OrbitalConnectionUsername")]
        public string OrbitalConnectionUsername { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrbitalConnectionPassword")]
        public string OrbitalConnectionPassword { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrderID")]
        public string OrderID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("Amount")]
        public string Amount { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TaxInd")]
        public string TaxInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("Tax")]
        public string Tax { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BIN")]
        public Valid_Routing_Bins BIN { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MerchantID")]
        public string MerchantID { get; set; }

        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 3.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(3)]
        [System.Xml.Serialization.XmlElementAttribute("TerminalID")]
        public string TerminalID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TxRefNum")]
        public string TxRefNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCOrderNum")]
        public string PCOrderNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCDestZip")]
        public string PCDestZip { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCDestName")]
        public string PCDestName { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCDestAddress1")]
        public string PCDestAddress1 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCDestAddress2")]
        public string PCDestAddress2 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCDestCity")]
        public string PCDestCity { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCDestState")]
        public string PCDestState { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AMEXTranAdvAddn1")]
        public string AMEXTranAdvAddn1 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AMEXTranAdvAddn2")]
        public string AMEXTranAdvAddn2 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AMEXTranAdvAddn3")]
        public string AMEXTranAdvAddn3 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AMEXTranAdvAddn4")]
        public string AMEXTranAdvAddn4 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3FreightAmt")]
        public string PC3FreightAmt { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3DutyAmt")]
        public string PC3DutyAmt { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3DestCountryCd")]
        public string PC3DestCountryCd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3ShipFromZip")]
        public string PC3ShipFromZip { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3DiscAmt")]
        public string PC3DiscAmt { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3VATtaxAmt")]
        public string PC3VATtaxAmt { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3VATtaxRate")]
        public string PC3VATtaxRate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3AltTaxInd")]
        public string PC3AltTaxInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3AltTaxID")]
        public string PC3AltTaxID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3AltTaxAmt")]
        public string PC3AltTaxAmt { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PC3LineItemCount")]
        public string PC3LineItemCount { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PC3LineItemType> _pC3LineItemArray;

        [System.Xml.Serialization.XmlArrayAttribute("PC3LineItemArray")]
        [System.Xml.Serialization.XmlArrayItemAttribute("PC3LineItem")]
        public System.Collections.ObjectModel.Collection<PC3LineItemType> PC3LineItemArray
        {
            get
            {
                return this._pC3LineItemArray;
            }
            private set
            {
                this._pC3LineItemArray = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die PC3LineItemArray-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the PC3LineItemArray collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PC3LineItemArraySpecified
        {
            get
            {
                return (this.PC3LineItemArray.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="MarkForCaptureType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MarkForCaptureType" /> class.</para>
        /// </summary>
        public MarkForCaptureType()
        {
            this._pC3LineItemArray = new System.Collections.ObjectModel.Collection<PC3LineItemType>();
        }

        [System.Xml.Serialization.XmlElementAttribute("PCardRequestorName")]
        public string PCardRequestorName { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCardLocalTaxRate")]
        public string PCardLocalTaxRate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCardNationalTax")]
        public string PCardNationalTax { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCardPstTaxRegNumber")]
        public string PCardPstTaxRegNumber { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCardCustomerVatRegNumber")]
        public string PCardCustomerVatRegNumber { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCardMerchantVatRegNumber")]
        public string PCardMerchantVatRegNumber { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCardTotalTaxAmount")]
        public string PCardTotalTaxAmount { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCardDtlTaxAmount1Ind")]
        public string PCardDtlTaxAmount1Ind { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCardDtlTaxAmount1")]
        public string PCardDtlTaxAmount1 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCardDtlTaxAmount2Ind")]
        public string PCardDtlTaxAmount2Ind { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCardDtlTaxAmount2")]
        public string PCardDtlTaxAmount2 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PinlessDebitTotalShpmnt")]
        public string PinlessDebitTotalShpmnt { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AuthenticationECIInd")]
        public string AuthenticationECIInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("DigitalTokenCryptogram")]
        public string DigitalTokenCryptogram { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("XID")]
        public string XID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SCATrustedMerchant")]
        public string SCATrustedMerchant { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SCASecureCorporatePayment")]
        public string SCASecureCorporatePayment { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SCATransactionRiskAnalysis")]
        public string SCATransactionRiskAnalysis { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SCALowValuePayment")]
        public string SCALowValuePayment { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SCAMerchantInitiatedTransaction")]
        public string SCAMerchantInitiatedTransaction { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SCARecurringPayment")]
        public string SCARecurringPayment { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SCADelegation")]
        public string SCADelegation { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MCProgramProtocol")]
        public string MCProgramProtocol { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MCDirectoryTransID")]
        public string MCDirectoryTransID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("UCAFInd")]
        public string UCAFInd { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("reversalType", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReversalType
    {

        [System.Xml.Serialization.XmlElementAttribute("OrbitalConnectionUsername")]
        public string OrbitalConnectionUsername { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrbitalConnectionPassword")]
        public string OrbitalConnectionPassword { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TxRefNum")]
        public string TxRefNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TxRefIdx")]
        public string TxRefIdx { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AdjustedAmt")]
        public string AdjustedAmt { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrderID")]
        public string OrderID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BIN")]
        public Valid_Routing_Bins BIN { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MerchantID")]
        public string MerchantID { get; set; }

        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 3.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(3)]
        [System.Xml.Serialization.XmlElementAttribute("TerminalID")]
        public string TerminalID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ReversalRetryNumber")]
        public string ReversalRetryNumber { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OnlineReversalInd")]
        public string OnlineReversalInd { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("endOfDayType", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EndOfDayType
    {

        [System.Xml.Serialization.XmlElementAttribute("OrbitalConnectionUsername")]
        public string OrbitalConnectionUsername { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrbitalConnectionPassword")]
        public string OrbitalConnectionPassword { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BIN")]
        public Valid_Routing_Bins BIN { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MerchantID")]
        public string MerchantID { get; set; }

        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 3.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(3)]
        [System.Xml.Serialization.XmlElementAttribute("TerminalID")]
        public string TerminalID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SettleRejectHoldingBin")]
        public SettleRejectHoldingBin SettleRejectHoldingBin { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SettleRejectHoldingBin", Namespace = "", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("SettleRejectHoldingBin", Namespace = "")]
    public partial class SettleRejectHoldingBin
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("inquiryType", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InquiryType
    {

        [System.Xml.Serialization.XmlElementAttribute("OrbitalConnectionUsername")]
        public string OrbitalConnectionUsername { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrbitalConnectionPassword")]
        public string OrbitalConnectionPassword { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BIN")]
        public Valid_Routing_Bins BIN { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MerchantID")]
        public string MerchantID { get; set; }

        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 3.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(3)]
        [System.Xml.Serialization.XmlElementAttribute("TerminalID")]
        public string TerminalID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrderID")]
        public string OrderID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("InquiryRetryNumber")]
        public string InquiryRetryNumber { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("accountUpdaterType", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountUpdaterType
    {

        [System.Xml.Serialization.XmlElementAttribute("OrbitalConnectionUsername")]
        public string OrbitalConnectionUsername { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrbitalConnectionPassword")]
        public string OrbitalConnectionPassword { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerBin")]
        public Valid_Routing_Bins CustomerBin { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerMerchantID")]
        public string CustomerMerchantID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerRefNum")]
        public string CustomerRefNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerProfileAction")]
        public string CustomerProfileAction { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ScheduledDate")]
        public string ScheduledDate { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("profileType", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProfileType
    {

        [System.Xml.Serialization.XmlElementAttribute("OrbitalConnectionUsername")]
        public string OrbitalConnectionUsername { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrbitalConnectionPassword")]
        public string OrbitalConnectionPassword { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerBin")]
        public Valid_Routing_Bins CustomerBin { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerMerchantID")]
        public string CustomerMerchantID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerName")]
        public string CustomerName { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerRefNum")]
        public string CustomerRefNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerAddress1")]
        public string CustomerAddress1 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerAddress2")]
        public string CustomerAddress2 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerCity")]
        public string CustomerCity { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerState")]
        public string CustomerState { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerZIP")]
        public string CustomerZIP { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerEmail")]
        public string CustomerEmail { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerPhone")]
        public string CustomerPhone { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerCountryCode")]
        public string CustomerCountryCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerProfileAction")]
        public Profile_Action_Types CustomerProfileAction { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerProfileOrderOverrideInd")]
        public string CustomerProfileOrderOverrideInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerProfileFromOrderInd")]
        public string CustomerProfileFromOrderInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrderDefaultDescription")]
        public string OrderDefaultDescription { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrderDefaultAmount")]
        public string OrderDefaultAmount { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerAccountType")]
        public string CustomerAccountType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("Status")]
        public string Status { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CCAccountNum")]
        public string CCAccountNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CCExpireDate")]
        public string CCExpireDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPAccountDDA")]
        public string ECPAccountDDA { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPAccountType")]
        public string ECPAccountType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPAccountRT")]
        public string ECPAccountRT { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPBankPmtDlv")]
        public string ECPBankPmtDlv { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SwitchSoloStartDate")]
        public string SwitchSoloStartDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SwitchSoloIssueNum")]
        public string SwitchSoloIssueNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBType")]
        public string MBType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBOrderIdGenerationMethod")]
        public string MBOrderIdGenerationMethod { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBRecurringStartDate")]
        public string MBRecurringStartDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBRecurringEndDate")]
        public string MBRecurringEndDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBRecurringNoEndDateFlag")]
        public string MBRecurringNoEndDateFlag { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBRecurringMaxBillings")]
        public string MBRecurringMaxBillings { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBRecurringFrequency")]
        public string MBRecurringFrequency { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBDeferredBillDate")]
        public string MBDeferredBillDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBMicroPaymentMaxDollarValue")]
        public string MBMicroPaymentMaxDollarValue { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBMicroPaymentMaxBillingDays")]
        public string MBMicroPaymentMaxBillingDays { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBMicroPaymentMaxTransactions")]
        public string MBMicroPaymentMaxTransactions { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBCancelDate")]
        public string MBCancelDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBRestoreBillingDate")]
        public string MBRestoreBillingDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBRemoveFlag")]
        public string MBRemoveFlag { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDCountryCode")]
        public string EUDDCountryCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDBankSortCode")]
        public string EUDDBankSortCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDRibCode")]
        public string EUDDRibCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SDMerchantName")]
        public string SDMerchantName { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SDProductDescription")]
        public string SDProductDescription { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SDMerchantCity")]
        public string SDMerchantCity { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SDMerchantPhone")]
        public string SDMerchantPhone { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SDMerchantURL")]
        public string SDMerchantURL { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SDMerchantEmail")]
        public string SDMerchantEmail { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BillerReferenceNumber")]
        public string BillerReferenceNumber { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AccountUpdaterEligibility")]
        public string AccountUpdaterEligibility { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDBankBranchCode")]
        public string EUDDBankBranchCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDIBAN")]
        public string EUDDIBAN { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDBIC")]
        public string EUDDBIC { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDMandateSignatureDate")]
        public string EUDDMandateSignatureDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDMandateID")]
        public string EUDDMandateID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDMandateType")]
        public string EUDDMandateType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("DPANInd")]
        public string DPANInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TokenRequestorID")]
        public string TokenRequestorID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MITMsgType")]
        public string MITMsgType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MITSubmittedTransactionID")]
        public string MITSubmittedTransactionID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PinlessDebitTxnType")]
        public string PinlessDebitTxnType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PinlessDebitMerchantUrl")]
        public string PinlessDebitMerchantUrl { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CardBrand")]
        public string CardBrand { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("profile-action-types", Namespace = "")]
    public enum Profile_Action_Types
    {

        C,

        R,

        U,

        D,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("flexCacheType", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FlexCacheType
    {

        [System.Xml.Serialization.XmlElementAttribute("OrbitalConnectionUsername")]
        public string OrbitalConnectionUsername { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrbitalConnectionPassword")]
        public string OrbitalConnectionPassword { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BIN")]
        public Valid_Routing_Bins BIN { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MerchantID")]
        public string MerchantID { get; set; }

        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 3.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(3)]
        [System.Xml.Serialization.XmlElementAttribute("TerminalID")]
        public string TerminalID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AccountNum")]
        public string AccountNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrderID")]
        public string OrderID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("Amount")]
        public string Amount { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CardSecVal")]
        public string CardSecVal { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("Comments")]
        public string Comments { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ShippingRef")]
        public string ShippingRef { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("IndustryType")]
        public Valid_Industry_Types IndustryType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FlexAutoAuthInd")]
        public Yes_Or_No FlexAutoAuthInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FlexPartialRedemptionInd")]
        public Yes_Or_No FlexPartialRedemptionInd { get; set; }

        /// <summary>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// <para xml:lang="en">Pattern: (([Bb][Aa][Ll][Aa][Nn][Cc][Ee][Ii][Nn][Qq][Uu][Ii][Rr][Yy]))|(([Aa][Dd][Dd][Vv][Aa][Ll][Uu][Ee]))|(([Rr][Ee][Ff][Uu][Nn][Dd]))|(([Aa][Uu][Tt][Hh]))|(([Aa][Cc][Tt][Ii][Vv][Aa][Tt][Ee]))|(([Dd][Ee][Aa][Cc][Tt][Ii][Vv][Aa][Tt][Ee]))|(([Rr][Ee][Aa][Cc][Tt][Ii][Vv][Aa][Tt][Ee]))|(([Rr][Ee][Dd][Ee][Mm][Pp][Tt][Ii][Oo][Nn][Cc][Oo][Mm][Pp][Ll][Ee][Tt][Ii][Oo][Nn]))|(([Rr][Ee][Dd][Ee][Mm][Pp][Tt][Ii][Oo][Nn]))|(([Vv][Oo][Ii][Dd])).</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(30)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute(@"(([Bb][Aa][Ll][Aa][Nn][Cc][Ee][Ii][Nn][Qq][Uu][Ii][Rr][Yy]))|(([Aa][Dd][Dd][Vv][Aa][Ll][Uu][Ee]))|(([Rr][Ee][Ff][Uu][Nn][Dd]))|(([Aa][Uu][Tt][Hh]))|(([Aa][Cc][Tt][Ii][Vv][Aa][Tt][Ee]))|(([Dd][Ee][Aa][Cc][Tt][Ii][Vv][Aa][Tt][Ee]))|(([Rr][Ee][Aa][Cc][Tt][Ii][Vv][Aa][Tt][Ee]))|(([Rr][Ee][Dd][Ee][Mm][Pp][Tt][Ii][Oo][Nn][Cc][Oo][Mm][Pp][Ll][Ee][Tt][Ii][Oo][Nn]))|(([Rr][Ee][Dd][Ee][Mm][Pp][Tt][Ii][Oo][Nn]))|(([Vv][Oo][Ii][Dd]))")]
        [System.Xml.Serialization.XmlElementAttribute("FlexAction")]
        public string FlexAction { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("StartAccountNum")]
        public string StartAccountNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ActivationCount")]
        public string ActivationCount { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TxRefNum")]
        public string TxRefNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FlexEmployeeNumber")]
        public string FlexEmployeeNumber { get; set; }

        /// <summary>
        /// <para xml:lang="en">Maximum length: 6.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(6)]
        [System.Xml.Serialization.XmlElementAttribute("PriorAuthID")]
        public string PriorAuthID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSzip")]
        public string AVSzip { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSaddress1")]
        public string AVSaddress1 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSaddress2")]
        public string AVSaddress2 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVScity")]
        public string AVScity { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSstate")]
        public string AVSstate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSphoneNum")]
        public string AVSphoneNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSname")]
        public string AVSname { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVScountryCode")]
        public string AVScountryCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDestzip")]
        public string AVSDestzip { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDestaddress1")]
        public string AVSDestaddress1 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDestaddress2")]
        public string AVSDestaddress2 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDestcity")]
        public string AVSDestcity { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDeststate")]
        public string AVSDeststate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDestphoneNum")]
        public string AVSDestphoneNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDestname")]
        public string AVSDestname { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDestcountryCode")]
        public string AVSDestcountryCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerAni")]
        public string CustomerAni { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSPhoneType")]
        public string AVSPhoneType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSDestPhoneType")]
        public string AVSDestPhoneType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerEmail")]
        public string CustomerEmail { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerIpAddress")]
        public string CustomerIpAddress { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EmailAddressSubtype")]
        public string EmailAddressSubtype { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerBrowserName")]
        public string CustomerBrowserName { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ShippingMethod")]
        public string ShippingMethod { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FraudAnalysis")]
        public FraudAnalysisType FraudAnalysis { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("yes-or-no", Namespace = "")]
    public enum Yes_Or_No
    {

        /// <summary>
        /// <para>Yes</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Yes")]
        Y,

        /// <summary>
        /// <para>Yes</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Yes")]
        [System.Xml.Serialization.XmlEnumAttribute("y")]
        Y1,

        /// <summary>
        /// <para>No</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("No")]
        N,

        /// <summary>
        /// <para>No</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("No")]
        [System.Xml.Serialization.XmlEnumAttribute("n")]
        N1,
    }

    /// <summary>
    /// <para>Top level element for all XML request transaction types</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Top level element for all XML request transaction types")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Request", Namespace = "", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Request", Namespace = "")]
    public partial class Request
    {

        [System.Xml.Serialization.XmlElementAttribute("AccountUpdater")]
        public AccountUpdaterType AccountUpdater { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("Inquiry")]
        public InquiryType Inquiry { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("NewOrder")]
        public NewOrderType NewOrder { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EndOfDay")]
        public EndOfDayType EndOfDay { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FlexCache")]
        public FlexCacheType FlexCache { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("Profile")]
        public ProfileType Profile { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("Reversal")]
        public ReversalType Reversal { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MarkForCapture")]
        public MarkForCaptureType MarkForCapture { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SafetechFraudAnalysis")]
        public SafetechFraudAnalysisType SafetechFraudAnalysis { get; set; }
    }
}
