//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.421.0.
namespace PaymentechCore.Models.ResponseModels
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("fraudAnalysisRespType", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FraudAnalysisRespType
    {

        [System.Xml.Serialization.XmlElementAttribute("FraudScoreIndicator")]
        public string FraudScoreIndicator { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FraudStatusCode")]
        public string FraudStatusCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RiskInquiryTransactionID")]
        public string RiskInquiryTransactionID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AutoDecisionResponse")]
        public string AutoDecisionResponse { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RiskScore")]
        public string RiskScore { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("KaptchaMatchFlag")]
        public string KaptchaMatchFlag { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("WorstCountry")]
        public string WorstCountry { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerRegion")]
        public string CustomerRegion { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PaymentBrand")]
        public string PaymentBrand { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FourteenDayVelocity")]
        public string FourteenDayVelocity { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SixHourVelocity")]
        public string SixHourVelocity { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerNetwork")]
        public string CustomerNetwork { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("NumberOfDevices")]
        public string NumberOfDevices { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("NumberOfCards")]
        public string NumberOfCards { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("NumberOfEmails")]
        public string NumberOfEmails { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("DeviceLayers")]
        public string DeviceLayers { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("DeviceFingerprint")]
        public string DeviceFingerprint { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerTimeZone")]
        public string CustomerTimeZone { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerLocalDateTime")]
        public string CustomerLocalDateTime { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("DeviceRegion")]
        public string DeviceRegion { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("DeviceCountry")]
        public string DeviceCountry { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ProxyStatus")]
        public string ProxyStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("JavascriptStatus")]
        public string JavascriptStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FlashStatus")]
        public string FlashStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CookiesStatus")]
        public string CookiesStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BrowserCountry")]
        public string BrowserCountry { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BrowserLanguage")]
        public string BrowserLanguage { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MobileDeviceIndicator")]
        public string MobileDeviceIndicator { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MobileDeviceType")]
        public string MobileDeviceType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MobileWirelessIndicator")]
        public string MobileWirelessIndicator { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("VoiceDevice")]
        public string VoiceDevice { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PCRemoteIndicator")]
        public string PCRemoteIndicator { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RulesDataLength")]
        public string RulesDataLength { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RulesData")]
        public string RulesData { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("safetechFraudAnalysisRespType", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SafetechFraudAnalysisRespType
    {

        [System.Xml.Serialization.XmlElementAttribute("IndustryType")]
        public string IndustryType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MerchantID")]
        public string MerchantID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TerminalID")]
        public string TerminalID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CardBrand")]
        public string CardBrand { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AccountNum")]
        public string AccountNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrderID")]
        public string OrderID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TxRefNum")]
        public string TxRefNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RespTime")]
        public string RespTime { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ProcStatus")]
        public string ProcStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ApprovalStatus")]
        public string ApprovalStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RespCode")]
        public string RespCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("StatusMsg")]
        public string StatusMsg { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RespMsg")]
        public string RespMsg { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("HostRespCode")]
        public string HostRespCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerRefNum")]
        public string CustomerRefNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerName")]
        public string CustomerName { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ProfileProcStatus")]
        public string ProfileProcStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerProfileMessage")]
        public string CustomerProfileMessage { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FraudAnalysisResponse")]
        public FraudAnalysisRespType FraudAnalysisResponse { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDCountryCode")]
        public string EUDDCountryCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDBankSortCode")]
        public string EUDDBankSortCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDRibCode")]
        public string EUDDRibCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDBankBranchCode")]
        public string EUDDBankBranchCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDIBAN")]
        public string EUDDIBAN { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDBIC")]
        public string EUDDBIC { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("newOrderRespType", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewOrderRespType
    {

        [System.Xml.Serialization.XmlElementAttribute("IndustryType")]
        public string IndustryType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MessageType")]
        public string MessageType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MerchantID")]
        public string MerchantID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TerminalID")]
        public string TerminalID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CardBrand")]
        public string CardBrand { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AccountNum")]
        public string AccountNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrderID")]
        public string OrderID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TxRefNum")]
        public string TxRefNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TxRefIdx")]
        public string TxRefIdx { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ProcStatus")]
        public string ProcStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ApprovalStatus")]
        public string ApprovalStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RespCode")]
        public string RespCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSRespCode")]
        public string AVSRespCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CVV2RespCode")]
        public string CVV2RespCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AuthCode")]
        public string AuthCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RecurringAdviceCd")]
        public string RecurringAdviceCd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CAVVRespCode")]
        public string CAVVRespCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("StatusMsg")]
        public string StatusMsg { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RespMsg")]
        public string RespMsg { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("HostRespCode")]
        public string HostRespCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("HostAVSRespCode")]
        public string HostAVSRespCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("HostCVV2RespCode")]
        public string HostCVV2RespCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerRefNum")]
        public string CustomerRefNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerName")]
        public string CustomerName { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ProfileProcStatus")]
        public string ProfileProcStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerProfileMessage")]
        public string CustomerProfileMessage { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BillerReferenceNumber")]
        public string BillerReferenceNumber { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBStatus")]
        public string MBStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBMicroPaymentDaysLeft")]
        public string MBMicroPaymentDaysLeft { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBMicroPaymentDollarsLeft")]
        public string MBMicroPaymentDollarsLeft { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RespTime")]
        public string RespTime { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PartialAuthOccurred")]
        public string PartialAuthOccurred { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RequestedAmount")]
        public string RequestedAmount { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RedeemedAmount")]
        public string RedeemedAmount { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RemainingBalance")]
        public string RemainingBalance { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CountryFraudFilterStatus")]
        public string CountryFraudFilterStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("IsoCountryCode")]
        public string IsoCountryCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FraudScoreProcStatus")]
        public string FraudScoreProcStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FraudScoreProcMsg")]
        public string FraudScoreProcMsg { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FraudAnalysisResponse")]
        public FraudAnalysisRespType FraudAnalysisResponse { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CTIAffluentCard")]
        public string CTIAffluentCard { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CTICommercialCard")]
        public string CTICommercialCard { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CTIDurbinExemption")]
        public string CTIDurbinExemption { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CTIHealthcareCard")]
        public string CTIHealthcareCard { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CTILevel3Eligible")]
        public string CTILevel3Eligible { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CTIPayrollCard")]
        public string CTIPayrollCard { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CTIPrepaidCard")]
        public string CTIPrepaidCard { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CTIPINlessDebitCard")]
        public string CTIPINlessDebitCard { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CTISignatureDebitCard")]
        public string CTISignatureDebitCard { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CTIIssuingCountry")]
        public string CTIIssuingCountry { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDCountryCode")]
        public string EUDDCountryCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDBankSortCode")]
        public string EUDDBankSortCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDRibCode")]
        public string EUDDRibCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDBankBranchCode")]
        public string EUDDBankBranchCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDIBAN")]
        public string EUDDIBAN { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDBIC")]
        public string EUDDBIC { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDMandateSignatureDate")]
        public string EUDDMandateSignatureDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDMandateID")]
        public string EUDDMandateID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDMandateType")]
        public string EUDDMandateType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TokenAssuranceLevel")]
        public string TokenAssuranceLevel { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("DPANAccountStatus")]
        public string DPANAccountStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSAccountStatusCode")]
        public string EWSAccountStatusCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSAOAConditionCode")]
        public string EWSAOAConditionCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSNameMatch")]
        public string EWSNameMatch { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSFirstNameMatch")]
        public string EWSFirstNameMatch { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSMiddleNameMatch")]
        public string EWSMiddleNameMatch { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSLastNameMatch")]
        public string EWSLastNameMatch { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSBusinessNameMatch")]
        public string EWSBusinessNameMatch { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSAddressMatch")]
        public string EWSAddressMatch { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSCityMatch")]
        public string EWSCityMatch { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSStateMatch")]
        public string EWSStateMatch { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSZipMatch")]
        public string EWSZipMatch { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSPhoneMatch")]
        public string EWSPhoneMatch { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSSSNTINMatch")]
        public string EWSSSNTINMatch { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSDOBMatch")]
        public string EWSDOBMatch { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSIDTypeMatch")]
        public string EWSIDTypeMatch { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSIDNumberMatch")]
        public string EWSIDNumberMatch { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EWSIDStateMatch")]
        public string EWSIDStateMatch { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FXOptOutInd")]
        public string FXOptOutInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FXRateHandlingInd")]
        public string FXRateHandlingInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FXRateID")]
        public string FXRateID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FXExchangeRate")]
        public string FXExchangeRate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FXPresentmentCurrency")]
        public string FXPresentmentCurrency { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FXSettlementCurrency")]
        public string FXSettlementCurrency { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FXDefaultRateInd")]
        public string FXDefaultRateInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FXRateStatus")]
        public string FXRateStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MITReceivedTransactionID")]
        public string MITReceivedTransactionID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RtauUpdatedCardNum")]
        public string RtauUpdatedCardNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RtauUpdatedCardExp")]
        public string RtauUpdatedCardExp { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RtauResponseCode")]
        public string RtauResponseCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVConsumerAccountDate")]
        public string AVConsumerAccountDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SafetechToken")]
        public string SafetechToken { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("inquiryRespType", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InquiryRespType
    {

        [System.Xml.Serialization.XmlElementAttribute("IndustryType")]
        public string IndustryType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MessageType")]
        public string MessageType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MerchantID")]
        public string MerchantID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TerminalID")]
        public string TerminalID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CardBrand")]
        public string CardBrand { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AccountNum")]
        public string AccountNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrderID")]
        public string OrderID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TxRefNum")]
        public string TxRefNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TxRefIdx")]
        public string TxRefIdx { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ProcStatus")]
        public string ProcStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ApprovalStatus")]
        public string ApprovalStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RespCode")]
        public string RespCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSRespCode")]
        public string AVSRespCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CVV2RespCode")]
        public string CVV2RespCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AuthCode")]
        public string AuthCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RecurringAdviceCd")]
        public string RecurringAdviceCd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CAVVRespCode")]
        public string CAVVRespCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("StatusMsg")]
        public string StatusMsg { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RespMsg")]
        public string RespMsg { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("HostRespCode")]
        public string HostRespCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("HostAVSRespCode")]
        public string HostAVSRespCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("HostCVV2RespCode")]
        public string HostCVV2RespCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerRefNum")]
        public string CustomerRefNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerName")]
        public string CustomerName { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ProfileProcStatus")]
        public string ProfileProcStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerProfileMessage")]
        public string CustomerProfileMessage { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BillerReferenceNumber")]
        public string BillerReferenceNumber { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBStatus")]
        public string MBStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBMicroPaymentDaysLeft")]
        public string MBMicroPaymentDaysLeft { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBMicroPaymentDollarsLeft")]
        public string MBMicroPaymentDollarsLeft { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RespTime")]
        public string RespTime { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PartialAuthOccurred")]
        public string PartialAuthOccurred { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RequestedAmount")]
        public string RequestedAmount { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RedeemedAmount")]
        public string RedeemedAmount { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RemainingBalance")]
        public string RemainingBalance { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CountryFraudFilterStatus")]
        public string CountryFraudFilterStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("IsoCountryCode")]
        public string IsoCountryCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FraudScoreProcStatus")]
        public string FraudScoreProcStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FraudScoreProcMsg")]
        public string FraudScoreProcMsg { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FraudAnalysisResponse")]
        public FraudAnalysisRespType FraudAnalysisResponse { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CTIAffluentCard")]
        public string CTIAffluentCard { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CTICommercialCard")]
        public string CTICommercialCard { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CTIDurbinExemption")]
        public string CTIDurbinExemption { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CTIHealthcareCard")]
        public string CTIHealthcareCard { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CTILevel3Eligible")]
        public string CTILevel3Eligible { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CTIPayrollCard")]
        public string CTIPayrollCard { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CTIPrepaidCard")]
        public string CTIPrepaidCard { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CTIPINlessDebitCard")]
        public string CTIPINlessDebitCard { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CTISignatureDebitCard")]
        public string CTISignatureDebitCard { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CTIIssuingCountry")]
        public string CTIIssuingCountry { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDCountryCode")]
        public string EUDDCountryCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDBankSortCode")]
        public string EUDDBankSortCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDRibCode")]
        public string EUDDRibCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDBankBranchCode")]
        public string EUDDBankBranchCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDIBAN")]
        public string EUDDIBAN { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDBIC")]
        public string EUDDBIC { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDMandateSignatureDate")]
        public string EUDDMandateSignatureDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDMandateID")]
        public string EUDDMandateID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDMandateType")]
        public string EUDDMandateType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TokenAssuranceLevel")]
        public string TokenAssuranceLevel { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("DPANAccountStatus")]
        public string DPANAccountStatus { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("accountUpdaterRespType", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountUpdaterRespType
    {

        [System.Xml.Serialization.XmlElementAttribute("customerBin")]
        public string CustomerBin { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("customerMerchantID")]
        public string CustomerMerchantID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerRefNum")]
        public string CustomerRefNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerProfileAction")]
        public string CustomerProfileAction { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("Status")]
        public string Status { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ScheduledDate")]
        public string ScheduledDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ProfileProcStatus")]
        public string ProfileProcStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerProfileMessage")]
        public string CustomerProfileMessage { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RespTime")]
        public string RespTime { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("markForCaptureRespType", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MarkForCaptureRespType
    {

        [System.Xml.Serialization.XmlElementAttribute("MerchantID")]
        public string MerchantID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TerminalID")]
        public string TerminalID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrderID")]
        public string OrderID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TxRefNum")]
        public string TxRefNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TxRefIdx")]
        public string TxRefIdx { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("Amount")]
        public string Amount { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ProcStatus")]
        public string ProcStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("StatusMsg")]
        public string StatusMsg { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RespTime")]
        public string RespTime { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ApprovalStatus")]
        public string ApprovalStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RespCode")]
        public string RespCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AVSRespCode")]
        public string AVSRespCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AuthCode")]
        public string AuthCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RespMsg")]
        public string RespMsg { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("HostRespCode")]
        public string HostRespCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("HostAVSRespCode")]
        public string HostAVSRespCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TxnSurchargeAmt")]
        public string TxnSurchargeAmt { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TokenAssuranceLevel")]
        public string TokenAssuranceLevel { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("DPANAccountStatus")]
        public string DPANAccountStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MITReceivedTransactionID")]
        public string MITReceivedTransactionID { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("reversalRespType", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReversalRespType
    {

        [System.Xml.Serialization.XmlElementAttribute("MerchantID")]
        public string MerchantID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TerminalID")]
        public string TerminalID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrderID")]
        public string OrderID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TxRefNum")]
        public string TxRefNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TxRefIdx")]
        public string TxRefIdx { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OutstandingAmt")]
        public string OutstandingAmt { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ProcStatus")]
        public string ProcStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("StatusMsg")]
        public string StatusMsg { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RespTime")]
        public string RespTime { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MITReceivedTransactionID")]
        public string MITReceivedTransactionID { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("endOfDayRespType", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EndOfDayRespType
    {

        [System.Xml.Serialization.XmlElementAttribute("MerchantID")]
        public string MerchantID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TerminalID")]
        public string TerminalID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BatchSeqNum")]
        public string BatchSeqNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ProcStatus")]
        public string ProcStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("StatusMsg")]
        public string StatusMsg { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SettleRejectHoldingBin")]
        public SettleRejectHoldingBin SettleRejectHoldingBin { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RespTime")]
        public string RespTime { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SettleRejectHoldingBin", Namespace = "", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("SettleRejectHoldingBin", Namespace = "")]
    public partial class SettleRejectHoldingBin
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("profileRespType", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProfileRespType
    {

        [System.Xml.Serialization.XmlElementAttribute("CustomerBin")]
        public string CustomerBin { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerMerchantID")]
        public string CustomerMerchantID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerName")]
        public string CustomerName { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerRefNum")]
        public string CustomerRefNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerProfileAction")]
        public string CustomerProfileAction { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ProfileProcStatus")]
        public string ProfileProcStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerProfileMessage")]
        public string CustomerProfileMessage { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerAddress1")]
        public string CustomerAddress1 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerAddress2")]
        public string CustomerAddress2 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerCity")]
        public string CustomerCity { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerState")]
        public string CustomerState { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerZIP")]
        public string CustomerZIP { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerEmail")]
        public string CustomerEmail { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerPhone")]
        public string CustomerPhone { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerCountryCode")]
        public string CustomerCountryCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerProfileOrderOverrideInd")]
        public string CustomerProfileOrderOverrideInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrderDefaultDescription")]
        public string OrderDefaultDescription { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrderDefaultAmount")]
        public string OrderDefaultAmount { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerAccountType")]
        public string CustomerAccountType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("Status")]
        public string Status { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CardBrand")]
        public string CardBrand { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CCAccountNum")]
        public string CCAccountNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CCExpireDate")]
        public string CCExpireDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPAccountDDA")]
        public string ECPAccountDDA { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPAccountType")]
        public string ECPAccountType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPAccountRT")]
        public string ECPAccountRT { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPBankPmtDlv")]
        public string ECPBankPmtDlv { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SwitchSoloStartDate")]
        public string SwitchSoloStartDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SwitchSoloIssueNum")]
        public string SwitchSoloIssueNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerMBStatus")]
        public string CustomerMBStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBType")]
        public string MBType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBOrderIdGenerationMethod")]
        public string MBOrderIdGenerationMethod { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBRecurringStartDate")]
        public string MBRecurringStartDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBRecurringEndDate")]
        public string MBRecurringEndDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBRecurringNoEndDateFlag")]
        public string MBRecurringNoEndDateFlag { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBRecurringMaxBillings")]
        public string MBRecurringMaxBillings { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBRecurringFrequency")]
        public string MBRecurringFrequency { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBDeferredBillDate")]
        public string MBDeferredBillDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBMicroPaymentMaxDollarValue")]
        public string MBMicroPaymentMaxDollarValue { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBMicroPaymentMaxBillingDays")]
        public string MBMicroPaymentMaxBillingDays { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBMicroPaymentMaxTransactions")]
        public string MBMicroPaymentMaxTransactions { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBCustomerStatus")]
        public string MBCustomerStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBMicroPaymentDaysLeft")]
        public string MBMicroPaymentDaysLeft { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MBMicroPaymentDollarsLeft")]
        public string MBMicroPaymentDollarsLeft { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDCountryCode")]
        public string EUDDCountryCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDBankSortCode")]
        public string EUDDBankSortCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDRibCode")]
        public string EUDDRibCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SDMerchantName")]
        public string SDMerchantName { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SDProductDescription")]
        public string SDProductDescription { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SDMerchantCity")]
        public string SDMerchantCity { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SDMerchantPhone")]
        public string SDMerchantPhone { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SDMerchantURL")]
        public string SDMerchantURL { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SDMerchantEmail")]
        public string SDMerchantEmail { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BillerReferenceNumber")]
        public string BillerReferenceNumber { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RespTime")]
        public string RespTime { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AccountUpdaterEligibility")]
        public string AccountUpdaterEligibility { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDBankBranchCode")]
        public string EUDDBankBranchCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDIBAN")]
        public string EUDDIBAN { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDBIC")]
        public string EUDDBIC { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDMandateSignatureDate")]
        public string EUDDMandateSignatureDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDMandateID")]
        public string EUDDMandateID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EUDDMandateType")]
        public string EUDDMandateType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("DPANInd")]
        public string DPANInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TokenRequestorID")]
        public string TokenRequestorID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MITMsgType")]
        public string MITMsgType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MITSubmittedTransactionID")]
        public string MITSubmittedTransactionID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PinlessDebitTxnType")]
        public string PinlessDebitTxnType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("PinlessDebitMerchantUrl")]
        public string PinlessDebitMerchantUrl { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SafetechToken")]
        public string SafetechToken { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("flexCacheRespType", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FlexCacheRespType
    {

        [System.Xml.Serialization.XmlElementAttribute("MerchantID")]
        public string MerchantID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TerminalID")]
        public string TerminalID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrderID")]
        public string OrderID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AccountNum")]
        public string AccountNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("StartAccountNum")]
        public string StartAccountNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("BatchFailedAcctNum")]
        public string BatchFailedAcctNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FlexRequestedAmount")]
        public string FlexRequestedAmount { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FlexRedeemedAmt")]
        public string FlexRedeemedAmt { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FlexHostTrace")]
        public string FlexHostTrace { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FlexAction")]
        public string FlexAction { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FlexAcctBalance")]
        public string FlexAcctBalance { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FlexAcctPriorBalance")]
        public string FlexAcctPriorBalance { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FlexAcctExpireDate")]
        public string FlexAcctExpireDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CardBrand")]
        public string CardBrand { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TxRefNum")]
        public string TxRefNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TxRefIdx")]
        public string TxRefIdx { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ProcStatus")]
        public string ProcStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("StatusMsg")]
        public string StatusMsg { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ApprovalStatus")]
        public string ApprovalStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AuthCode")]
        public string AuthCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RespCode")]
        public string RespCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CVV2RespCode")]
        public string CVV2RespCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AutoAuthTxRefIdx")]
        public string AutoAuthTxRefIdx { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AutoAuthTxRefNum")]
        public string AutoAuthTxRefNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AutoAuthProcStatus")]
        public string AutoAuthProcStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AutoAuthStatusMsg")]
        public string AutoAuthStatusMsg { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AutoAuthApprovalStatus")]
        public string AutoAuthApprovalStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AutoAuthFlexRedeemedAmt")]
        public string AutoAuthFlexRedeemedAmt { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AutoAuthAuthCode")]
        public string AutoAuthAuthCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AutoAuthRespCode")]
        public string AutoAuthRespCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AutoAuthFlexHostTrace")]
        public string AutoAuthFlexHostTrace { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AutoAuthFlexAction")]
        public string AutoAuthFlexAction { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AutoAuthRespTime")]
        public string AutoAuthRespTime { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RespTime")]
        public string RespTime { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FraudScoreProcStatus")]
        public string FraudScoreProcStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FraudScoreProcMsg")]
        public string FraudScoreProcMsg { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("FraudAnalysisResponse")]
        public FraudAnalysisRespType FraudAnalysisResponse { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("quickRespType", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QuickRespType
    {

        [System.Xml.Serialization.XmlElementAttribute("MerchantID")]
        public string MerchantID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TerminalID")]
        public string TerminalID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrderID")]
        public string OrderID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AccountNum")]
        public string AccountNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("StartAccountNum")]
        public string StartAccountNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TxRefNum")]
        public string TxRefNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TxRefIdx")]
        public string TxRefIdx { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ProcStatus")]
        public string ProcStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("StatusMsg")]
        public string StatusMsg { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ApprovalStatus")]
        public string ApprovalStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerBin")]
        public string CustomerBin { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerMerchantID")]
        public string CustomerMerchantID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerName")]
        public string CustomerName { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerRefNum")]
        public string CustomerRefNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerProfileAction")]
        public string CustomerProfileAction { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ProfileProcStatus")]
        public string ProfileProcStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerProfileMessage")]
        public string CustomerProfileMessage { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerAddress1")]
        public string CustomerAddress1 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerAddress2")]
        public string CustomerAddress2 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerCity")]
        public string CustomerCity { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerState")]
        public string CustomerState { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerZIP")]
        public string CustomerZIP { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerEmail")]
        public string CustomerEmail { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerPhone")]
        public string CustomerPhone { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerProfileOrderOverrideInd")]
        public string CustomerProfileOrderOverrideInd { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrderDefaultDescription")]
        public string OrderDefaultDescription { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrderDefaultAmount")]
        public string OrderDefaultAmount { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerAccountType")]
        public string CustomerAccountType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CCAccountNum")]
        public string CCAccountNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CCExpireDate")]
        public string CCExpireDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPAccountDDA")]
        public string ECPAccountDDA { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPAccountType")]
        public string ECPAccountType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPAccountRT")]
        public string ECPAccountRT { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ECPBankPmtDlv")]
        public string ECPBankPmtDlv { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SwitchSoloStartDate")]
        public string SwitchSoloStartDate { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SwitchSoloIssueNum")]
        public string SwitchSoloIssueNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RespTime")]
        public string RespTime { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("quickRespType_old", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QuickRespType_Old
    {

        [System.Xml.Serialization.XmlElementAttribute("MerchantID")]
        public string MerchantID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TerminalID")]
        public string TerminalID { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ProcStatus")]
        public string ProcStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("StatusMsg")]
        public StatusMsg StatusMsg { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ApprovalStatus")]
        public string ApprovalStatus { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TxRefIdx")]
        public string TxRefIdx { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("TxRefNum")]
        public string TxRefNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("OrderNumber")]
        public string OrderNumber { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AccountNum")]
        public string AccountNum { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("POSEntryMode")]
        public string POSEntryMode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CardType1")]
        public string CardType1 { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("RespTime")]
        public string RespTime { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("CustomerProfileResponse")]
        public string CustomerProfileResponse { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private QuickRespType_OldHcsTcsInd _hcsTcsInd = PaymentechCore.Models.ResponseModels.QuickRespType_OldHcsTcsInd.T;

        [System.ComponentModel.DefaultValueAttribute(PaymentechCore.Models.ResponseModels.QuickRespType_OldHcsTcsInd.T)]
        [System.Xml.Serialization.XmlAttributeAttribute("HcsTcsInd")]
        public QuickRespType_OldHcsTcsInd HcsTcsInd
        {
            get
            {
                return this._hcsTcsInd;
            }
            set
            {
                this._hcsTcsInd = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute("MessageType")]
        public QuickRespType_OldMessageType MessageType { get; set; }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die MessageType-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the MessageType property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MessageTypeSpecified { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _version = "2";

        [System.ComponentModel.DefaultValueAttribute("2")]
        [System.Xml.Serialization.XmlAttributeAttribute("Version")]
        public string Version
        {
            get
            {
                return this._version;
            }
            set
            {
                this._version = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute("CapStatus")]
        public QuickRespType_OldCapStatus CapStatus { get; set; }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die CapStatus-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CapStatus property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CapStatusSpecified { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _langInd = "00";

        [System.ComponentModel.DefaultValueAttribute("00")]
        [System.Xml.Serialization.XmlAttributeAttribute("LangInd")]
        public string LangInd
        {
            get
            {
                return this._langInd;
            }
            set
            {
                this._langInd = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute("TzCode")]
        public string TzCode { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StatusMsg", Namespace = "")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("StatusMsg", Namespace = "")]
    public partial class StatusMsg
    {

        /// <summary>
        /// <para xml:lang="de">Ruft den Text ab oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("StatusMsgLth")]
        public string StatusMsgLth { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("QuickRespType_OldHcsTcsInd", Namespace = "", AnonymousType = true)]
    public enum QuickRespType_OldHcsTcsInd
    {

        T,

        H,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("QuickRespType_OldMessageType", Namespace = "", AnonymousType = true)]
    public enum QuickRespType_OldMessageType
    {

        FR,

        PR,

        V,

        A,

        AC,

        C,

        B,

        UC,

        U,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("QuickRespType_OldCapStatus", Namespace = "", AnonymousType = true)]
    public enum QuickRespType_OldCapStatus
    {

        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,

        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,

        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,

        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,

        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
    }

    /// <summary>
    /// <para>Response XML for all defined Request transactions</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Response XML for all defined Request transactions")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.421.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Response", Namespace = "", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Response", Namespace = "")]
    public partial class Response
    {

        [System.Xml.Serialization.XmlElementAttribute("FlexCacheResp")]
        public FlexCacheRespType FlexCacheResp { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("NewOrderResp")]
        public NewOrderRespType NewOrderResp { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ProfileResp")]
        public ProfileRespType ProfileResp { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("EndOfDayResp")]
        public EndOfDayRespType EndOfDayResp { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("ReversalResp")]
        public ReversalRespType ReversalResp { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("MarkForCaptureResp")]
        public MarkForCaptureRespType MarkForCaptureResp { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("QuickResp")]
        public QuickRespType QuickResp { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("QuickResponse")]
        public QuickRespType_Old QuickResponse { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("InquiryResp")]
        public InquiryRespType InquiryResp { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("AccountUpdaterResp")]
        public AccountUpdaterRespType AccountUpdaterResp { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("SafetechFraudAnalysisResp")]
        public SafetechFraudAnalysisRespType SafetechFraudAnalysisResp { get; set; }
    }
}
